### PR TITLE
From react

### PR DESCRIPTION
**Pull request by weyj4**

### CODE REVIEW

**Comment by jaumard** [comment]
https://github.com/trailsjs/trails/blob/master/archetype/config/webpack.js need to be remove from master repo too :)
So with this, is `trailpack-react` really useful ? Because it do nothing without the webpack config right ?

**Comment by weyj4** [comment]
`trailpack-react` really doesn't serve a purpose right now. In the past we'd talked about building in react support for trails, but other than `trailpack-webpack` I'm not sure what would be needed. I guess we could have some prebuilt React landing page components.

@jaumard maybe you can help me-when I symlink `npm link` to `trailpack-webpack` from `trailsmix` I get an error about the `babel-preset-react` not found relative to my local `trailpack-webpack`. The react preset should be installed by the user in their base app. I'm thinking once this is on npm and gets installed in `node_modules` that might solve itself. Have you had a similar problem before?

**Comment by jaumard** [comment]
@weyj4 I have similar problem with `trailpack-express4` ! And it make me crazy :( under `config/views` if I put engine to jade everything is working because jade was a trailpack dependency by if I put ejs it's not working at all even installed on the project.... If you found the solution I want it :D because for now to add ejs I put `require('ejs')__express`...

Yeah not sure `trailpack-react` should exist... It's all webpack|gulp|... configuration... Maybe we can do something with the generator instead to generate the front configuration instead... Just thinking..

**Comment by weyj4** [comment]
Yes, looks like express' consolidate plugin has a similar problem with directory structure. Oh well.

Do you think we should go ahead and put this on npm? We need trailpack-webpack for other projects (trailsmix) and I'm not sure how else to test it.

**Comment by jaumard** [comment]
@weyj4 sure you can put it on npm because normally the trailpack is working so no problem, if I remember even with the `trailpack-express4` from npm I need to use `require` to have ejs as template :/ let me know ! :)

**Pull request merged**
